### PR TITLE
How to do agile software development

### PR DESCRIPTION
**Pull request by mchubinsky**

### CODE REVIEW

**Comment by debbhad** [comment]
@mchubinsky This is very comprehensive! I would just love to have a little bit more color on epics and stories, especially if you could show with an example what could be an epic and what could be the corresponding stories within it.

**Comment by mchubinsky** [comment]
@NT01 and @ebibby89 – what do you think? @debbhad and @sdm-2016, thanks for your comments

**Comment by NT01** [comment]
@mchubinsky Well done! I know that you mentioned testing after completion in your post, however, I also remember learning that it is very important to tell the development team how you will test the feature before they start. I think this really helps clarify the desired functionality before any software is built. Perhaps, this could fit somewhere in the learning.

**Comment by ebibby89** [comment]
@mchubinsky Looks good to me! I really like your closing paragraph of laying out the steps simply. Easy for anyone to follow.

**Comment by sdm-2016** [comment]
@mchubinsky :+1: This looks great. As Deb said, this is a comprehensive overview. I would certainly use this as a reference on Agile software development in my future.

**Comment by mchubinsky** [comment]
@sdm-2016 and @ebibby89 thanks for the kind words. @debbhad @NT01 made your changes. Good to go?

**Comment by NT01** [comment]
@mchubinsky :+1: Good to go!

**Comment by debbhad** [comment]
:+1: Good to go!

**Pull request merged**
