### PR TITLE
Create How to start building a product?

### PR DESCRIPTION
**Pull request by debbhad**
@NT01 : Nate, have I created a branch and pull request in the right way?

@NT01 @sdm-2016 @mchubinsky @ebibby89 : Hey guys, this is a summary of my key learnings from the course and I would be grateful if you can provide some feedback on this. Also, happy to provide any further clarifications. Cheers!

### CODE REVIEW

**Comment by sdm-2016** [comment]
@debbhad Looks good! The lessons about prioritization are great to note. I would be interested in even more detail here, i.e. talk about the process and trade-offs to consider when prioritizing.

**Comment by debbhad** [comment]
@sdm-2016 : Thanks for your comment! I tried fleshing out the details on prioritization a little more. Kindly let me know if it is clearer now.

**Comment by mchubinsky** [comment]
Nice job @debbhad. You might consider elaborating about why a mobile-optimized site is generally a good low-cost option or the different considerations that go into choosing between sites versus apps.

**Comment by NT01** [comment]
@debbhad Great job! One other thing that stood out to me from the course is the idea that one should try to build as little software as possible. For instance, if you wanted to build an ecommerce platform, rather than start from scratch, you might want to build your site through shopify as they have already optimized all of the ecommerce functionality, this way would be much less expensive, and it could be built more quickly. Perhaps, something like this could be added to the learning.

**Comment by ebibby89** [comment]
@debbhad good job! The article you linked to was clear and informative as well.

**Comment by debbhad** [comment]
@sdm-2016 @mchubinsky @NT01  : Guys, thanks for your really thoughtful comments! I have tried to incorporate as much as I can in my write-up. Would be great if you can go through it and let me know in case you have any specific comments. In case you guys are good to go, would be great if you can send me a :+1: 

@ebibby89 : Thanks for your comment, Glad that you liked the link. Do you have any other specific comments or are you good to go? Thanks!

**Comment by sdm-2016** [comment]
@debbhad Great updates here! :+1: Looks ready to :ship: Appreciate the additional detail on prioritization, per my earlier comment, and the further updates. Nicely done (and great photo)

**Comment by mchubinsky** [comment]
:+1: :shipit:

**Comment by NT01** [comment]
@debbhad :+1: good to go!

**Pull request merged**
