### PR TITLE
New lesson addition: how to start before you build

### PR DESCRIPTION
**Pull request by sdm-2016**

### CODE REVIEW

**Comment by sdm-2016** [comment]
@ebibby89 @mchubinsky @NT01 @debbhad Would love your feedback on the ideas here. Communicating lessons for the many considerations we learned about before actually developing a piece of software.

**Comment by debbhad** [comment]
@sdm-2016 Great job! Very well articulated! Would be great if you can provide some more color on the second lesson - "do things that don't scale" as that is counter-intuitive to general wisdom. Thanks!

**Comment by mchubinsky** [comment]
@sdm-2016 I love it. Great picture. Maybe add a link to Paul Graham's website or Wikipedia page so that I can learn even more!

**Comment by NT01** [comment]
@sdm-2016 Well done! Very well articulated! When reading through all of the different ways to learn about your customers and what they want, I was reminded of the concept of A/B testing (also called split testing) that I had read about in the Lean Startup. Perhaps, you might want to include this as an example as well. If you want to learn more, here is a link to the concept on wikipedia: https://en.wikipedia.org/wiki/Lean_startup#Split_testing. Otherwise, awesome!

**Comment by ebibby89** [comment]
@sdm-2016 This was a really important topic to bring up. It's illustrated very nicely with the graphic you selected. You also nailed it with the formatting and hyperlinks!

**Comment by debbhad** [comment]
@sdm-2016 : could you also tell us how you embedded the hyperlinks into the text? Thanks!

**Comment by sdm-2016** [comment]
@ebibby89 @mchubinsky @NT01 @debbhad Thank you for all the comments and suggestions! Would you all take a look at the updated version?

**Comment by sdm-2016** [comment]
Also, for @debbhad request on the hyperlinks, use this format:
1. List the text to display in square brackets [ ]
2. Have the url right next to it in parentheses ( )

Github changes this immediately to that format if I show you an example on here, so hope that helps!

**Comment by mchubinsky** [comment]
Good to go :+1:

**Comment by NT01** [comment]
@sdm-2016 :+1: Good to go!

**Comment by debbhad** [comment]
:+1: good to go!

**Pull request merged**
