### PR TITLE
Created lesson on how to build a development team

### PR DESCRIPTION
**Pull request by NT01**
@mchubinsky @ebibby89 @debbhad @sdm-2016 Would love to get your thinking on what else we should add to our lesson learned on building a development team!

@peterbell Does it look like we have forked the repo right (i.e. NT01/lessons-learned), created a distinct feature branch (i.e. how-to-build-a-development-team), and the pull request to get feedback on the how-to-build-a-development-team.md file the right way?

### CODE REVIEW

**Comment by debbhad** [comment]
@NT01 : This is a great write-up Nate! Summarizes the last class really well. I had a quick comment - maybe you can write a couple of lines about the book 'The Pragmatic Programmer' as its an evergreen book and almost a must for every programmer to read and also a great book for people who are looking to hire programmers.

**Comment by sdm-2016** [comment]
@NT01 Nice! The lessons about hiring a development team were very insightful for future business managers, in my opinion. On the section (towards the end) about having developers in office: you mention that if not in office, could go international. We had also discussed that even when international, prefer to stay in same / similar time zones first (e.g. Chile), then thinking about cross-time zones (e.g. India). May be worth adding a note like that.

**Comment by mchubinsky** [comment]
@NT01 Super! I'm not sure I agree with your best to worst hierarchy of sourcing talent. Maybe you meant "easiest to hardest?"

**Comment by NT01** [comment]
@debbhad @sdm-2016 @mchubinsky I built in all of your feedback. @debbhad great point on commenting on the Pragmatic Programmer. @sdm-2016 Your comment on timezones is spot on. @mchubinsky You are right; not sure that classification was correct. I decided to remove that language entirely. @ebibby89 Any other thoughts?

**Comment by ebibby89** [comment]
@NT01 I think this was really nicely done. Super thorough. Maybe other helpful information is on what hiring a development team might cost you...such as hiring a developer right out of a training program, vs. a 4-year college, vs. one with a few years of experience.

**Comment by debbhad** [comment]
@NT01 : Thanks for incorporating all the comments. this is good to go from my side! :+1:

**Comment by sdm-2016** [comment]
@NT01 Great work! :+1: Looks good to go, and thanks for adding in the further points about developer locations.

**Comment by mchubinsky** [comment]
:+1:

**Comment by NT01** [comment]
@mchubinsky @sdm-2016 @ebibby89 @debbhad Thanks for all your feedback. Going to merge.

**Pull request merged**
