### PR TITLE
Website vs app the debate

### PR DESCRIPTION
**Pull request by ebibby89**
Maybe I've done it now? @NT01 @sdm-2016 @mchubinsky @debbhad

### CODE REVIEW

**Comment by mchubinsky** [comment]
Nice @ebibby89 Maybe add a line about how even if you start with a website, you can create an app out of if relatively simply using PhoneGap or Cordova.

**Comment by ebibby89** [comment]
Thanks @mchubinsky! I made this addition.

**Comment by NT01** [comment]
@ebibby89 Looks good to me! Good to ship :+1:

**Comment by NT01** [comment]
@ebibby89 Looks good! Perhaps, you also want to mention that when building an app, you usually have to consider building for two platforms: ios and android devices. This really compounds cost and complexity of making the choice to build an app.

**Comment by ebibby89** [comment]
@NT01 thank you! I also added in your point, and agree it's good to call out that factor.

**Comment by debbhad** [comment]
@ebibby89 Great writeup! The only suggestion from my side would be to write a line on how deciding b/w a website and an app is also dependent on the target segment for the product and how they use the product. Thanks.

**Comment by ebibby89** [comment]
Thank you @debbhad ! Am I ready to ship everyone? Appreciate all your comments. @mchubinsky @NT01 @mchubinsky @sdm-2016

**Comment by debbhad** [comment]
:+1: Good to go from my side!

**Comment by mchubinsky** [comment]
Looks good :+1: :shipit:

**Comment by NT01** [comment]
@ebibby89 :+1: Good to go!

**Pull request merged**
